import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:printing/printing.dart';
import 'package:intl/intl.dart';
import 'package:paywise/models/loan_model.dart';

class PdfService {
  Future<void> generateAndPrint(LoanModel loan, List<AmortizationRow> schedule) async {
    final pdf = pw.Document();
    
    // Use "Rs." to avoid box character issues
    final currency = NumberFormat.currency(locale: "en_IN", symbol: "Rs. ", decimalDigits: 2);
    final dateFormat = DateFormat('MMM yyyy');

    pdf.addPage(
      pw.MultiPage(
        pageFormat: PdfPageFormat.a4,
        build: (pw.Context context) {
          return [
            pw.Header(
              level: 0,
              child: pw.Row(
                mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
                children: [
                  pw.Text('Amortization Schedule', style: pw.TextStyle(fontSize: 24, fontWeight: pw.FontWeight.bold)),
                  pw.Text('Generated by Loan Management', style: const pw.TextStyle(fontSize: 12, color: PdfColors.grey)),
                ],
              ),
            ),
            pw.SizedBox(height: 20),
            pw.Container(
              padding: const pw.EdgeInsets.all(10),
              decoration: pw.BoxDecoration(border: pw.Border.all()),
              child: pw.Column(
                crossAxisAlignment: pw.CrossAxisAlignment.start,
                children: [
                  pw.Text('Loan Title: ${loan.title}', style: pw.TextStyle(fontWeight: pw.FontWeight.bold)),
                  pw.Text('Lender: ${loan.lenderName}'),
                  pw.Text('Principal: ${currency.format(loan.principalAmount)}'),
                  pw.Text('Interest Rate: ${loan.interestRate}%'),
                  pw.Text('Tenure: ${loan.tenureMonths} Months'),
                ],
              ),
            ),
            pw.SizedBox(height: 20),
            
            // Table
            pw.TableHelper.fromTextArray(
              headers: ['Month', 'EMI', 'Principal', 'Interest', 'Balance'],
              data: schedule.map((row) {
                // FIXED: row is now strictly typed, so .month is definitely an int
                final date = DateTime.now().add(Duration(days: 30 * row.month));
                return [
                  dateFormat.format(date),
                  currency.format(row.emi),
                  currency.format(row.principalComponent),
                  currency.format(row.interestComponent),
                  currency.format(row.closingBalance),
                ];
              }).toList(),
              headerStyle: pw.TextStyle(fontWeight: pw.FontWeight.bold, color: PdfColors.white),
              headerDecoration: const pw.BoxDecoration(color: PdfColors.indigo),
              rowDecoration: const pw.BoxDecoration(border: pw.Border(bottom: pw.BorderSide(width: 0.5, color: PdfColors.grey300))),
              cellAlignment: pw.Alignment.centerRight, 
              headerAlignment: pw.Alignment.centerRight,
              cellAlignments: {0: pw.Alignment.centerLeft}, 
            ),
          ];
        },
      ),
    );

    await Printing.layoutPdf(
      onLayout: (PdfPageFormat format) async => pdf.save(),
    );
  }
}
