// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'config/env_config.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static FirebaseOptions get android => FirebaseOptions(
    apiKey: EnvConfig.firebaseApiKey.isNotEmpty
        ? EnvConfig.firebaseApiKey
        : 'AIzaSyCEwbenQ-B8cLVB6WtRPTRpGbBU7FWEkN4',
    appId: EnvConfig.firebaseAppId.isNotEmpty
        ? EnvConfig.firebaseAppId
        : '1:416506927819:android:15f14c3f910558bd80594e',
    messagingSenderId: EnvConfig.firebaseMessagingSenderId.isNotEmpty
        ? EnvConfig.firebaseMessagingSenderId
        : '416506927819',
    projectId: EnvConfig.firebaseProjectId.isNotEmpty
        ? EnvConfig.firebaseProjectId
        : 'paywise-kp1504',
    databaseURL: EnvConfig.firebaseDatabaseUrl.isNotEmpty
        ? EnvConfig.firebaseDatabaseUrl
        : 'https://paywise-kp1504-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: EnvConfig.firebaseStorageBucket.isNotEmpty
        ? EnvConfig.firebaseStorageBucket
        : 'paywise-kp1504.firebasestorage.app',
  );

  static FirebaseOptions get ios => FirebaseOptions(
    apiKey: EnvConfig.firebaseApiKey.isNotEmpty
        ? EnvConfig.firebaseApiKey
        : 'AIzaSyBc8vpTmzHnskplpRBTvaSZzDnkn8yEK3A',
    appId: EnvConfig.firebaseAppId.isNotEmpty
        ? EnvConfig.firebaseAppId
        : '1:416506927819:ios:545c8672250c56dd80594e',
    messagingSenderId: EnvConfig.firebaseMessagingSenderId.isNotEmpty
        ? EnvConfig.firebaseMessagingSenderId
        : '416506927819',
    projectId: EnvConfig.firebaseProjectId.isNotEmpty
        ? EnvConfig.firebaseProjectId
        : 'paywise-kp1504',
    databaseURL: EnvConfig.firebaseDatabaseUrl.isNotEmpty
        ? EnvConfig.firebaseDatabaseUrl
        : 'https://paywise-kp1504-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: EnvConfig.firebaseStorageBucket.isNotEmpty
        ? EnvConfig.firebaseStorageBucket
        : 'paywise-kp1504.firebasestorage.app',
    androidClientId: '416506927819-7mip51sfjkijiru3pnqp23mti6m59qvq.apps.googleusercontent.com',
    iosClientId: '416506927819-640knv0ncvf5dc72hrerspb4mn8mli03.apps.googleusercontent.com',
    iosBundleId: 'com.pipal.paywise',
  );
}
