import 'package:flutter/material.dart';
import 'package:paywise/theme/glass_theme.dart';

class TermsConditionsScreen extends StatefulWidget {
  const TermsConditionsScreen({super.key});

  @override
  State<TermsConditionsScreen> createState() => _TermsConditionsScreenState();
}

class _TermsConditionsScreenState extends State<TermsConditionsScreen> {
  final ValueNotifier<bool> _isScrolled = ValueNotifier<bool>(false);

  @override
  void dispose() {
    _isScrolled.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    final isDark = Theme.of(context).brightness == Brightness.dark;
    final topPadding = MediaQuery.of(context).padding.top;
    final totalTopPadding = topPadding + kToolbarHeight + 16;

    return Scaffold(
      extendBodyBehindAppBar: true,
      appBar: AppBar(
        title: const Text(
          'Terms & Conditions',
          style: TextStyle(fontWeight: FontWeight.bold, fontSize: 20),
        ),
        elevation: 0,
        backgroundColor: Colors.transparent,
        foregroundColor: isDark ? Colors.white : const Color(0xFF1E1E1E),
        leading: IconButton(
          icon: const Icon(Icons.arrow_back_ios_new_rounded, size: 20),
          tooltip: 'Back',
          onPressed: () => Navigator.of(context).pop(),
        ),
        flexibleSpace: GlassTheme.frostedAppBarFlexibleSpace(
          context,
          isScrolledNotifier: _isScrolled,
        ),
      ),
      body: GlassBackground(
        child: ScrolledNotificationWrapper(
          isScrolledNotifier: _isScrolled,
          child: SingleChildScrollView(
            padding: EdgeInsets.fromLTRB(16, totalTopPadding, 16, 60),
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                _buildHeroHeader(context, isDark),
                const SizedBox(height: 20),

                _buildTermsCard(
                  context,
                  isDark: isDark,
                  icon: Icons.gavel_rounded,
                  iconColor: Colors.deepPurpleAccent,
                  title: "1. Acceptance of Terms",
                  content:
                      "By downloading, accessing, or using the PayWise application on Android or iOS, you agree to be bound by these Terms & Conditions and our Privacy Policy. If you do not agree to these terms, please do not use the application.",
                ),
                const SizedBox(height: 14),

                _buildTermsCard(
                  context,
                  isDark: isDark,
                  icon: Icons.calculate_rounded,
                  iconColor: Colors.blueAccent,
                  title: "2. Financial Calculation Tool Disclaimer",
                  content:
                      "PayWise is an analytical calculation, debt tracking, and budgeting utility. PayWise is not a bank, non-banking financial company (NBFC), registered financial advisor, or lending institution. PayWise does not issue loans, disburse funds, or provide licensed financial, tax, or investment advice.",
                ),
                const SizedBox(height: 14),

                _buildTermsCard(
                  context,
                  isDark: isDark,
                  icon: Icons.auto_graph_rounded,
                  iconColor: Colors.teal,
                  title: "3. Amortization & Estimate Accuracy",
                  content:
                      "Amortization tables, monthly EMI calculations, prepayment savings estimations, and debt-free projections generated by PayWise are mathematical models based on the standard Reducing Balance formula. Actual amounts charged by your specific lending institution may differ marginally due to institution-specific conventions, leap-year interest accruals, rounding methods, holiday moratoriums, or additional administrative fees.",
                ),
                const SizedBox(height: 14),

                _buildTermsCard(
                  context,
                  isDark: isDark,
                  icon: Icons.lock_outline_rounded,
                  iconColor: Colors.amber[800] ?? Colors.amber,
                  title: "4. Account Security & Biometrics",
                  content:
                      "You are solely responsible for maintaining the confidentiality of your login credentials and ensuring the physical security of your mobile device. When using Biometric Authentication (Fingerprint or Face ID), authentication is handled natively by your device operating system's Secure Enclave. PayWise incorporates brute-force defense mechanisms (limiting failed sign-in attempts) to safeguard your profile against unauthorized access.",
                ),
                const SizedBox(height: 14),

                _buildTermsCard(
                  context,
                  isDark: isDark,
                  icon: Icons.privacy_tip_rounded,
                  iconColor: Colors.green,
                  title: "5. Privacy & User Data Ownership",
                  content:
                      "Your financial records belong exclusively to you. PayWise does not read your private SMS inbox, does not scrape bank accounts, and does not sell or distribute your personal or financial data to advertising brokers or credit bureaus. You have the full right to export, modify, or permanently delete your account data at any time.",
                ),
                const SizedBox(height: 14),

                _buildTermsCard(
                  context,
                  isDark: isDark,
                  icon: Icons.notifications_active_rounded,
                  iconColor: Colors.indigoAccent,
                  title: "6. Push Notification Reminders",
                  content:
                      "EMI payment reminder notifications are scheduled locally using native operating system alarm mechanisms (Android AlarmManager and iOS Notification Center). While PayWise strives to deliver reminders reliably across multiple advance checkpoints, device-specific battery savers, third-party task killers, or disabled system notification permissions may affect background alert delivery. You remain responsible for satisfying your payment commitments with your lenders on time.",
                ),
                const SizedBox(height: 14),

                _buildTermsCard(
                  context,
                  isDark: isDark,
                  icon: Icons.shield_outlined,
                  iconColor: Colors.redAccent,
                  title: "7. Limitation of Liability",
                  content:
                      "To the maximum extent permitted by applicable law, PayWise and its developers shall not be liable for any indirect, incidental, consequential, or punitive damages arising from the use of, or inability to use, the application, including but not limited to late payment fees levied by third-party lenders, credit score alterations, or calculation variances.",
                ),
                const SizedBox(height: 14),

                _buildTermsCard(
                  context,
                  isDark: isDark,
                  icon: Icons.update_rounded,
                  iconColor: Colors.cyan,
                  title: "8. Modifications to Terms",
                  content:
                      "We reserve the right to modify these Terms & Conditions to reflect software enhancements, security updates, or statutory requirements. Continued use of the application following any posted modifications constitutes acceptance of the updated terms.",
                ),
                const SizedBox(height: 24),

                _buildFooter(context, isDark),
              ],
            ),
          ),
        ),
      ),
    );
  }

  Widget _buildHeroHeader(BuildContext context, bool isDark) {
    return Container(
      width: double.infinity,
      padding: const EdgeInsets.all(20),
      decoration: BoxDecoration(
        color: isDark ? const Color(0xFF1E1E2C) : Colors.white,
        borderRadius: BorderRadius.circular(20),
        border: Border.all(
          color: isDark ? const Color(0xFF2E2E3E) : const Color(0xFFCBD5E1),
        ),
      ),
      child: Row(
        children: [
          Container(
            padding: const EdgeInsets.all(12),
            decoration: BoxDecoration(
              color: Colors.deepPurpleAccent.withValues(alpha: 0.12),
              borderRadius: BorderRadius.circular(16),
            ),
            child: const Icon(
              Icons.article_rounded,
              color: Colors.deepPurpleAccent,
              size: 28,
            ),
          ),
          const SizedBox(width: 16),
          Expanded(
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                Text(
                  "PayWise User Agreement",
                  style: TextStyle(
                    fontSize: 16,
                    fontWeight: FontWeight.bold,
                    color: isDark ? Colors.white : const Color(0xFF1E293B),
                  ),
                ),
                const SizedBox(height: 4),
                Text(
                  "Effective Date: October 2026 • Version 1.0",
                  style: TextStyle(
                    fontSize: 12.5,
                    color: isDark ? Colors.grey[400] : const Color(0xFF64748B),
                  ),
                ),
              ],
            ),
          ),
        ],
      ),
    );
  }

  Widget _buildTermsCard(
    BuildContext context, {
    required bool isDark,
    required IconData icon,
    required Color iconColor,
    required String title,
    required String content,
  }) {
    return Container(
      width: double.infinity,
      padding: const EdgeInsets.all(18),
      decoration: BoxDecoration(
        color: isDark ? const Color(0xFF1E1E2C) : Colors.white,
        borderRadius: BorderRadius.circular(18),
        border: Border.all(
          color: isDark ? const Color(0xFF2E2E3E) : const Color(0xFFE2E8F0),
        ),
      ),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Row(
            children: [
              Container(
                padding: const EdgeInsets.all(8),
                decoration: BoxDecoration(
                  color: iconColor.withValues(alpha: 0.12),
                  borderRadius: BorderRadius.circular(10),
                ),
                child: Icon(icon, color: iconColor, size: 20),
              ),
              const SizedBox(width: 12),
              Expanded(
                child: Text(
                  title,
                  style: TextStyle(
                    fontSize: 15,
                    fontWeight: FontWeight.bold,
                    color: isDark ? Colors.white : const Color(0xFF0F172A),
                  ),
                ),
              ),
            ],
          ),
          const SizedBox(height: 12),
          Text(
            content,
            style: TextStyle(
              fontSize: 13.5,
              height: 1.55,
              color: isDark ? Colors.grey[300] : const Color(0xFF334155),
            ),
          ),
        ],
      ),
    );
  }

  Widget _buildFooter(BuildContext context, bool isDark) {
    return Center(
      child: Column(
        children: [
          Text(
            "PayWise • Personal Debt Command Center",
            style: TextStyle(
              fontSize: 13,
              fontWeight: FontWeight.w600,
              color: isDark ? Colors.grey[400] : const Color(0xFF64748B),
            ),
          ),
          const SizedBox(height: 4),
          Text(
            "© 2026 PayWise. All rights reserved.",
            style: TextStyle(
              fontSize: 12,
              color: isDark ? Colors.grey[500] : const Color(0xFF94A3B8),
            ),
          ),
        ],
      ),
    );
  }
}
